// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    partial class CityInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Big park",
                            Name = "New York"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Corrupt city",
                            Name = "Islamabad"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Materialistic",
                            Name = "Dubai"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dangerous city with knife crime.",
                            Name = "London"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Most visited park in the United States",
                            Name = "Central Park"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Famous commercial intersection",
                            Name = "Times Square"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Largest mosque in Pakistan",
                            Name = "Faisal Mosque"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            Description = "Tallest building in the world",
                            Name = "Burj Khalifa"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "Largest mall in the world",
                            Name = "The Dubai Mall"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 4,
                            Description = "Official residence of the monarch",
                            Name = "Buckingham Palace"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 4,
                            Description = "World-famous museum",
                            Name = "The British Museum"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "City")
                        .WithMany("PointsOfInterests")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
