# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  AZURE_WEBAPP_NAME: cityapi
  AZURE_WEBAPP_PACKAGE_PATH: "."
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Publish
      run: dotnet publish --no-restore --configuration Release 
    - name: Store build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
           src/CityInfo.API/bin/Release/net6.0/*.dll
  deploy:
    needs: build  
    runs-on: ubuntu-latest
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
    - name: Deploying to azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_WEBAPP_NAME}}
        publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE_CITYINFOAPI}}
        package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
        startup-command: 'dotnet CityInfo.API.dll'
