# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sjwebapp1

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  build:
    runs-on: 'ubuntu-latest'
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6e8ece5a406b417fb5048a499402751c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_864951c10ca340c9af3fb04664e93cd1 }}
    

    - name: Build and push container image to registry    
    
      uses: docker/build-push-action@v5
      with:
        push: true
        #tags: "index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6e8ece5a406b417fb5048a499402751c }}/dotnetcityapi:${{ github.sha }}"
        tags: index.docker.io/syedjunaiddocker/dotnetcityapi:${{ github.sha }}


        file: src/CityInfo.API/Dockerfile
    - name: Display Test Results
      shell: pwsh
      run: |
        $images = docker images
        echo $images
        $id =  docker images -q --filter "label=type=webapp"
        docker create --name testcontainer index.docker.io/syedjunaiddocker/dotnetcityapi:${{ github.sha }}
        docker cp testcontainer:/test-results ./test-results
        docker rm testcontainer
        ls
    - uses: dorny/test-reporter@v1
      with:
        name: UnitTest Results
        path: './test-results/test_results.trx'
        reporter: dotnet-trx
        fail-on-error: 'true'

    


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sjwebapp1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_42127056ecd740e8bb16238624f1a870 }}
        #images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6e8ece5a406b417fb5048a499402751c }}/dotnetcityapi:${{ github.sha }}'
        images: 'index.docker.io/syedjunaiddocker/dotnetcityapi:${{ github.sha }}'
